apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"
  volumeMode: Filesystem

--- 

apiVersion: v1
kind: Service
metadata:
  name: caddy-lb
spec:
  type: LoadBalancer
  ports:
  - name: http-caddy
    port: 80
    targetPort: 80
  - name: https-caddy
    port: 443
    targetPort: 443
  selector:
    app: caddy

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  selector:
    matchLabels:
      app: caddy
  replicas: 1
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        image: caddy:2.4.6-alpine
        env:
        - name: MW_SITE_FQDN
          valueFrom:
            configMapKeyRef:
              name: canasta-env
              key: MW_SITE_FQDN
        command: 
        - "caddy"
        - "reverse-proxy"
        - "--from"
        - "$(MW_SITE_FQDN)"
        - "--to"
        - "varnish:80"
        ports:
        - name: http-caddy
          containerPort: 80
        - name: https-caddy
          containerPort: 443
        volumeMounts:
          - name: caddy-data
            mountPath: /data
      volumes:
        - name: caddy-data
          persistentVolumeClaim:
            claimName: caddy-data
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: caddy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: caddy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
