apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  replicas: 1
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:3.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /var/log/mediawiki
          name: mediawiki-logs
          readOnly: true
        - mountPath: /var/log/caddy
          name: caddy-logs
          readOnly: true
        - mountPath: /var/log/mysql
          name: mysql-logs
          readOnly: true
        - mountPath: /fluent-bit/etc/fluent-bit.conf
          name: fluent-bit-conf
          subPath: fluent-bit.conf
        - mountPath: /fluent-bit/etc/parsers.conf
          name: fluent-bit-conf
          subPath: parsers.conf
      volumes:
      - name: mediawiki-logs
        persistentVolumeClaim:
          claimName: mediawiki-logs
          readOnly: true
      - name: caddy-logs
        persistentVolumeClaim:
          claimName: caddy-logs
          readOnly: true
      - name: mysql-logs
        persistentVolumeClaim:
          claimName: mysql-logs
          readOnly: true
      - name: fluent-bit-conf
        configMap:
          name: fluent-bit-config
