apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
      app: web
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sitemap-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"
  volumeMode: Filesystem

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ghcr.io/canastawiki/canasta:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: canasta-env
        volumeMounts:
        - mountPath: /var/www/mediawiki/w/user-extensions
          name: config-volume
          subPath: extensions
        - mountPath: /var/www/mediawiki/w/user-skins
          name: config-volume
          subPath: skins
        - mountPath: /mediawiki/config/wikis.yaml
          name: canasta-config
          subPath: wikis.yaml
        - mountPath: /mediawiki/config/Caddyfile
          name: canasta-config
          subPath: Caddyfile
        - mountPath: /mediawiki/config/Caddyfile.site
          name: canasta-config
          subPath: Caddyfile.site
        - mountPath: /mediawiki/config/Caddyfile.global
          name: canasta-config
          subPath: Caddyfile.global
        - mountPath: /mediawiki/config/default.vcl
          name: canasta-config
          subPath: default.vcl
        - mountPath: /mediawiki/config/my.cnf
          name: canasta-config
          subPath: my.cnf
        - mountPath: /mediawiki/config/settings/global
          name: canasta-settings-global
        - mountPath: /mediawiki/images
          name: config-volume
          subPath: images
        - name: sitemap-data
          mountPath: /mediawiki/sitemap
      volumes:
          - name: canasta-config
            configMap:
              name: canasta-config
          - name: canasta-settings-global
            configMap:
              name: canasta-settings-global
          - name: config-volume
            hostPath:
              path: /canasta/config-data
              type: DirectoryOrCreate
          - name: sitemap-data
            persistentVolumeClaim:
              claimName: sitemap-data
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
